---
- name: Install package dependencies.
  package: name={{ item }} state=present
  with_items:
    - unzip

- name: Download the awscli bundle.
  get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.2.41.zip dest=/tmp/awscli-bundle.zip
  register: aws_cli_download_bundle

- name: Unarchive the installer.
  unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no creates=/tmp/aws
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  #shell: python3 /tmp/aws/install -i /usr/local/aws -b /usr/bin/aws
  shell: |
     cd /tmp/aws
     sudo ./install
  when: aws_cli_unarchive_installer.changed

#- name: Configure AWS.
#  shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
#  no_log: True
#  with_dict:
#    aws_access_key_id: "{{ aws_access_key }}"
#    aws_secret_access_key: "{{ aws_secret_key }}"
#    region: "{{ aws_region }}"
#    format: "{{ aws_format }}"
#  become_user: "{{ aws_system_user }}"
#  changed_when: false